<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NeonetTransaction extends Model
{

    protected $table = 'neonet_transaction';

    protected $primaryKey = 'idneonet_transaction';

    protected $fillable = [
        'utf8',
        'req_card_number',
        'req_locale',
        'signature',
        'req_card_type_selection_indicator',
        'auth_trans_ref_no',
        'req_bill_to_surname',
        'req_bill_to_address_city',
        'req_card_expiry_date',
        'auth_cavv_result',
        'merchant_advice_code',
        'card_type_name',
        'reason_code',
        'auth_amount',
        'auth_response',
        'bill_trans_ref_no',
        'req_bill_to_forename',
        'req_payment_method',
        // 'request_token',
        'auth_cavv_result_raw',
        'auth_time',
        'req_amount',
        'req_bill_to_email',
        'auth_avs_code_raw',
        'transaction_id',
        'req_currency',
        'req_card_type',
        'decision',
        'message',
        // 'signed_field_names',
        'req_transaction_uuid',
        'auth_avs_code',
        'auth_code',
        'req_bill_to_address_country',
        'req_transaction_type',
        'req_access_key',
        'req_profile_id',
        'req_reference_number',
        'auth_reconciliation_reference_number',
        'signed_date_time',
        'req_bill_to_address_line1',
        'payment_idpayment',
    ];
}


        // 'auth_cv_result',
        // 'score_device_fingerprint_images_enabled',
        // 'score_score_result',
        // 'decision_case_priority',
        // 'score_rflag',
        // 'score_card_issuer',
        // 'score_rcode',
        // 'score_device_fingerprint_true_ipaddress_city',
        // 'decision_early_return_code',
        // 'score_device_fingerprint_true_ipaddress_attributes',
        // 'score_device_fingerprint_javascript_enabled',
        // 'score_ip_city',
        // 'score_device_fingerprint_screen_resolution',
        // 'score_velocity_info',
        // 'score_address_info',
        // 'score_model_used',
        // 'auth_cv_result_raw',
        // 'decision_rmsg',
        // 'score_device_fingerprint_cookies_enabled',
        // 'score_suspicious_info',
        // 'decision_rcode',
        // 'score_rmsg',
        // 'score_device_fingerprint_hash',
        // 'score_device_fingerprint_browser_language',
        // 'decision_rflag',
        // 'score_ip_state',
        // 'score_device_fingerprint_true_ipaddress',
        // 'score_ip_country',
        // 'score_card_scheme',
        // 'score_ip_routing_method',
        // 'score_device_fingerprint_true_ipaddress_country',
        // 'score_bin_country',
        // 'score_reason_code',
        // 'score_identity_info',
        // 'request_token',
        // 'req_device_fingerprint_id',
        // 'score_card_account_type',
        // 'decision_velocity_info',
        // 'score_device_fingerprint_smart_id_confidence_level',
        // 'decision_return_code',
        // 'decision_reason_code',
        // 'score_device_fingerprint_smart_id',
        // 'score_time_local',
        // 'score_return_code',
        // 'score_host_severity',
        // 'score_internet_info',
        // 'decision_early_reason_code',
        // 'score_device_fingerprint_flash_enabled',
        // 'decision_early_rcode',